title: kristina janovcikova
author: kristina janovcikova
theme: jekyll-theme-cayman

plugins:
  - jekyll
  - jekyll-paginate
  - jekyll-sitemap

# Exclude these files from production site
exclude:
  - LICENSE
  - README.md
  - TODO.md
  - Gemfile
  - Gemfile.lock